init_config: ~
instances: ~
logs: 
  - 
    path: /var/www/html/app/logs/prod/emailnotifications.log
    service: emailnotifications
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: emailnotifications
    type: file
  - 
    path: /var/www/html/app/logs/prod/import-queue.log
    service: import-queue
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: import-queue
    type: file
  - 
    path: /var/www/html/app/logs/prod/integration.log
    service: integration
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: integration
    type: file
  - 
    path: /var/www/html/app/logs/prod/list_import.log
    service: list_import
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: list_import
    type: file
  - 
    path: /var/www/html/app/logs/prod/payment_request.log
    service: payment_request
    source: DevStagingAPI
    sourcecategory: payment_request
    tags: fispan
    type: file
  - 
    path: /var/www/html/app/logs/prod/payments.log
    service: payments
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: payments
    type: file
  - 
    path: /var/www/html/app/logs/prod/prod.log
    service: prod.log
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: prod
    type: file
  - 
    path: /var/www/html/app/logs/prod/cron.log
    service: cron
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: cron
    type: file
  - 
    type: file
    path: /var/www/html/app/logs/prod/fispan.log
    service: fispan
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: fispan
  - 
    type: file
    path: /var/www/html/app/logs/prod/intercom-queue.log
    service: import-queue
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: import-queue
  - 
    type: file
    path: /var/www/html/app/logs/prod/cron_intercom.log
    service: cron_intercom
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: cron_intercom
  - 
    type: file
    path: /var/www/html/app/logs/prod/intercom_producer.log
    service: intercom_producer
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: intercom_producer
  - 
    path: /var/www/html/app/logs/prod/*.datadog
    service: testdatadog
    source: DevStagingAPI
    type: file
  - 
    type: file
    path: /var/www/html/app/logs/prod/auth.log
    service: authlog
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: authlog
  - 
    type: file
    path: /var/www/html/app/logs/prod/versapay_eft.log
    service: versapay_eft
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: versapay_eft
  - 
    type: file
    path: /var/www/html/app/logs/prod/orgunit_dismantler.log
    service: orgunit_dismantler
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: orgunit_dismantler
  - 
    type: file
    path: /var/www/html/app/logs/prod/intercom_worker.log
    service: intercom_worker
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: intercom_worker
  - 
    type: file
    path: /var/www/html/app/logs/prod/dismantler.log
    service: dismantler
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: dismantler
  - 
    type: file
    path: /var/www/html/app/logs/prod/image_import.log
    service: image_import
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: image_import
  - 
    type: file
    path: /var/www/html/app/logs/prod/cron_poimport.log
    service: cron_poimport
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: cron_poimport
  - 
    type: file
    path: /var/www/html/app/logs/prod/cron_newpoimport.log
    service: cron_newpoimport
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: cron_newpoimport
  - 
    type: file
    path: /var/www/html/app/logs/prod/cron_importer_producer.log
    service: cron_importer_producer
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: cron_importer_producer
  - 
    type: file
    path: /var/www/html/app/logs/prod/cron_images.log
    service: cron_images
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: cron_images
  - 
    type: file
    path: /var/www/html/app/logs/prod/cron_exports.log
    service: cron_exports
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: cron_exports
  - 
    type: file
    path: /var/www/html/app/logs/prod/rex-import-queue.log
    service: rex-import-queue
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: rex-import-queue
- 
    type: file
    path: /var/log/nginx/error.log
    service: nginx-error
    source: DevStagingAPI
    sourcecategory: sourcecode
    tags: nginx-error
